services:
  app:
    image: node:18-alpine
    container_name: markdown-editor
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8942:5173"
    # Ключевые изменения:
    user: "node"  # Используем встроенного пользователя из образа
    command: >
      sh -c "
      npm install &&
      npm run dev -- --host 0.0.0.0
      "
    restart: unless-stopped
    environment:
      - NODE_ENV=development